@startuml DiagramName
left to right direction

actor "Librarian" as librarian
actor "Member" as member
actor "Guest" as guest

rectangle "Library Management System" {
  usecase "Search Catalog" as searchCatalog
  usecase "Check Out Book" as checkOutBook
  usecase "Return Book" as returnBook
  usecase "Renew Book" as renewBook
  usecase "Manage Fines" as manageFines
  usecase "Add New Book" as addNewBook

  guest -- searchCatalog
  member -- checkOutBook
  member -- returnBook
  member -- renewBook
  librarian -- manageFines
  librarian -- addNewBook
}
@enduml
"""